### ISSUE TITLE
EIP-1167 - Minimal Proxy Contract

### ISSUE THREAD

**Issue by yarrumretep** [optionality/clone-factory#10]
Please use this issue for discussion of **EIP-1167 - Minimal Proxy Contract**

https://github.com/ethereum/EIPs/pull/1167

**Comment by yarrumretep** [comment]
We are planning to move this EIP to LAST CALL status today with a 2 week comment period.  Please submit any comments here.

**Comment by Recmo** [comment]
I wonder if that `swap1` can be eliminated or taken out of the branch.

**Comment by yarrumretep** [comment]
@Recmo - which swap1 are you thinking of - 0x2a or 0x2f in the deployed bytecode?

**Comment by Recmo** [comment]
Both. I'm having a bit of fun golfing the thing. To be clear, I have no problems finalizing the thing as is. But here's an potential optimization I found already:

The `push1 0x0` can be replaced by a cheaper and shorter `MSIZE` or `PC` which both evaluate to zero there.

**Comment by yarrumretep** [comment]
I think I see - do you mean pull the `returndatasize swap1` prior to the branch?  We decided not to do that so that we could 'reuse' the revert branch in the deployment code.  The alternative would be more deployment code for a bit less deployed code and zero operational gas savings (right?)

Happy to have this code golfed - let's enumerate all the improvements and evaluate if we would like to merge them.

You can make changes by modifying the javascript generator in the root of this project (optionality/clone-factory) and running the tests.

**Comment by Recmo** [comment]
Here's my stack annotation of the assembly. You could include it in the EIP:

```
     0x00000000      6000           push1 0x0          0
     0x00000002      36             calldatasize       cds 0
     0x00000003      81             dup2               0 cds 0
     0x00000004      80             dup1               0 0 cds 0
     0x00000005      37             calldatacopy       0
     0x00000006      80             dup1               0 0
     0x00000007      80             dup1               0 0 0
     0x00000008      36             calldatasize       cds 0 0 0
     0x00000009      81             dup2               0 cds 0 0 0
     0x0000000a      73bebebebebe.  push20 0xbebebebe  be 0 cds 0 0 0
     0x0000001f      5a             gas                gas be 0 cds 0 0 0
     0x00000020      f4             delegatecall       s 0
     0x00000021      3d             returndatasize     rds s 0
     0x00000022      82             dup3               0 rds s 0
     0x00000023      80             dup1               0 0 rds s 0
     0x00000024      3e             returndatacopy     rs 0
     0x00000025      15             iszero             zrs 0
     0x00000026      602c           push1 0x2c         2c brs 0
 ,=< 0x00000028      57             jumpi              0
 |   0x00000029      3d             returndatasize     rds 0
 |   0x0000002a      90             swap1              0 rds
 |   0x0000002b      f3             return             
 `-> 0x0000002c      5b             jumpdest           0
     0x0000002d      3d             returndatasize     rds 0
     0x0000002e      90             swap1              0 rds
     0x0000002f      fd             revert            
```

**Comment by Recmo** [comment]
* `returndatasize swap1` can be taken out of the loop. (need to check if it is a net saving)

**Comment by yarrumretep** [comment]
@Recmo - Love the stack annotation - will definitely add it!

Why on 0x24 does the 's' on your stack change to 'rs'?

**Comment by Recmo** [comment]
Typo. Edited the comment. Here's my current optimized for gas one:

```
     0x00000000      58             pc                 0
     0x00000001      36             calldatasize       cds 0
     0x00000002      81             dup2               0 cds 0
     0x00000003      80             dup1               0 0 cds 0
     0x00000004      37             calldatacopy       0
     0x00000005      80             dup1               0 0
     0x00000006      80             dup1               0 0 0
     0x00000007      36             calldatasize       cds 0 0 0
     0x00000008      81             dup2               0 cds 0 0 0
     0x00000009      73bebebebebe.  push20 0xbebebebe  be 0 cds 0 0 0
     0x0000001e      5a             gas                gas be 0 cds 0 0 0
     0x0000001f      f4             delegatecall       s 0
     0x00000020      3d             returndatasize     rds s 0
     0x00000021      82             dup3               0 rds s 0
     0x00000022      80             dup1               0 0 rds s 0
     0x00000023      3e             returndatacopy     s 0
     0x00000024      602c           push1 0x2c         2c s 0
 ,=< 0x00000026      57             jumpi              0
 |   0x00000027      3d             returndatasize     rds 0
 |   0x00000028      90             swap1              0 rds
 |   0x00000029      f3             revert             
 `-> 0x0000002a      5b             jumpdest           0
     0x0000002b      3d             returndatasize     rds 0
     0x0000002c      90             swap1              0 rds
     0x0000002d      fd             return            
```

**Comment by yarrumretep** [comment]
@Recmo - `pc` is the only change?

Need to change 0x24 to `push1 0x2a`

**Comment by Recmo** [comment]
And here is an optimized for size one. Note that it takes 3 more gas than the gas-optimized one:

```
     0x00000000      58             pc                 0
     0x00000001      36             calldatasize       cds 0
     0x00000002      81             dup2               0 cds 0
     0x00000003      80             dup1               0 0 cds 0
     0x00000004      37             calldatacopy       0
     0x00000005      80             dup1               0 0
     0x00000006      80             dup1               0 0 0
     0x00000007      36             calldatasize       cds 0 0 0
     0x00000008      81             dup2               0 cds 0 0 0
     0x00000009      73bebebebebe.  push20 0xbebebebe  be 0 cds 0 0 0
     0x0000001e      5a             gas                gas be 0 cds 0 0 0
     0x0000001f      f4             delegatecall       s 0
     0x00000020      3d             returndatasize     rds s 0
     0x00000021      82             dup3               0 rds s 0
     0x00000022      80             dup1               0 0 rds s 0
     0x00000023      3e             returndatacopy     s 0
     0x00000024      90             swap1              0 s
     0x00000025      3d             returndatasize     rds 0 s
     0x00000026      91             swap2              s 0 rds
     0x00000027      602b           push1 0x2b         2b s 0 rds
 ,=< 0x00000029      57             jumpi              0 rds
 |   0x0000002a      f3             revert             
 `-> 0x0000002b      5b             jumpdest           0 rds
     0x0000002c      fd             return             
```

**Comment by yarrumretep** [comment]
right - we elected to optimize for gas instead of taking the one-byte size improvement.

**Comment by yarrumretep** [comment]
@Remco - on the push20 line, it looks like the offset increment is different between yours and the generated disassembly from r2 .

**Comment by Recmo** [comment]
I'm hand updating the offsets, please don't take them to be correct. Same for the jump target. I'm still golfing the thing, and that stuff can be fixed in the end.

**Comment by yarrumretep** [comment]
Understood.  Love it - keep at it!  Let me know if you find anything else - and/or when you are done.  I'm inclined to put the `pc` improvement, but leave the cheaper operational setup with the branch.  Happy to hear arguments otherwise.

**Comment by Recmo** [comment]
I would go for the gas optimized one for sure. It does have a few more improvements than just `pc`, I added a short changelog for reverence. If would still suggest flipping the branches like I do in both versions, as this saves both gas an size. It's basically transforming `if(!s) A else B` into `if(s) B else A`.

**Comment by Recmo** [comment]
So it turns out `returndatasize` is the cheapestopcode to generate zeros right up untill the `delegatecall`. Makes for some funny code though :)

**Comment by yarrumretep** [comment]
Got it.  Thanks @Recmo - very fun!

**Comment by yarrumretep** [comment]
@Remco - you gonna raise a PR on the clone-factory project?  Or should I implement the changes from these notes?

**Comment by yarrumretep** [comment]
@Remco - I've implemented your improvements on branch golf-per-remco on this project.  You can take a look to see how it turned out.  I also eliminated the callvalue check in the intialization code (which is not part of the EIP just this implementation).  All it it measures as a savings of 617 gas per deployment and 5 gas per straightforward runtime invocation (no return value).

**Comment by maurelian** [comment]
This is excellent. Not really an issue about the EIP, but can you provide some details about the additional gas cost per call? I think it would be have a fixed component plus a variable based on the call data?

**Comment by Recmo** [comment]
@maurelian It's a bit more complex than that because of the quadratic cost of memory. AFAIK the exact formula of the overhead will be of the form:

```
proxy_gas = source_gas +  C + 3 * (n + m + k) + Floor[ k * k / 512 ]
```

where 

```
C = some constant, I expect it around 800
n = Ceil[ calldatasize / 32 ]
m = Ceil[ returndatasize / 32 ]
k = max(n, m)
```

**Comment by cag** [comment]
Hey guys, really great stuff here!

A few discussion points before the end is nigh (I'm sorry for procrastinating :sweat: ):

---

This implementation is a bit at odds with [EIP 897](https://eips.ethereum.org/EIPS/eip-897). The proxy target can always implement `ERCProxy` though, if it knows it is meant to be a proxy target. In any case, EIP 897 is still a draft, and this EIP locking an implementation down to allow checking the actual bytecode for determining whether or not something is a minimal proxy also means source code verification for the forwarding proxy case is covered.

I don't personally think this point is a blocker, but I do feel that this is worth mentioning in the discussion thread, so here we are.

---

Should we be trying to golf the implementation portion, or can that be optimized after the specification? I have a few nascent ideas that may take the gas costs down for the factory and probe:

* There may be a factory optimization in putting a whole word instead of going byte by byte. So like putting `(0xf36000368180378080368173 << 160) | uint(target)` in the appropriate place.
* Checking the `keccak256` hashes of the code before and after the variable bit instead of comparing byte by byte (word by word...?).

With that said, if the intention for the reference implementations are to be readable, then I would save these optimizations for an implementer (maybe this repo? I dunno if this is supposed to contain the reference implementation, or _some_ implementation).

--

Conversely, the reference implementation for the probe actually covers cases where the vanity address trick is used, though I don't see the vanity address trick mentioned in the body of the EIP. Maybe this optimization is worth mentioning in the EIP?

**Comment by fulldecent** [comment]
This EIP has the goal of "standardizing on a known minimal bytecode redirect implementation" so I believe golfing is IN SCOPE to block finalization of this EIP.

---

I believe the functionality of the proxy is not specified clearly enough and test cases are lacking. How can I confirm the proxy is working correctly? If the test case is well defined I should be able to compare the proposed implementation against other golfed implementations to find if they would be a better candidate.

Is it sufficient to test one function with a return value and one with no return value? If so can such a contract (in Solidity) please be provided as a test case? At present it is not convenient to validate the contract.

**Comment by yarrumretep** [comment]
@fulldecent - Thank you for the comments.  The deployment code included is currently that generated by Solidity.  No question that it can be improved. Rather than debate the deployment code in the context of the EIP itself, let's eliminate it from the specification entirely.  The EIP is really meant to get agreement on the runtime proxy contract bytecode.  This bytecode theoretically can be launched by whatever deployment bootstrap code the user wants.  The reference implementation should show a "best practice" deployment which should be minimal as well.

We have implemented an improved deployment bootstrap on the "golf-per-remco" branch of this repository - along with remco's suggested golfing from above.

**Comment by yarrumretep** [comment]
Based on feedback, EIP-1167 ( https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1167.md ) was updated in the following ways:

* Specification includes code-golf runtime gas improvements
* Specification includes vanity-address based proxy deployment gas improvements
* Removed Factory and Probe code from the EIP as they are not part of the standard - they are tooling that implements / utilizes the standard.

The plan is to keep the EIP in “last call” status, but extend the comment period for an additional two weeks to allow for reaction to these changes.

**Comment by fulldecent** [comment]
Here is the tail end of the code:

```
|           0x00000024      90             swap1                 0 suc
|           0x00000025      3d             returndatasize        rds 0 suc
|           0x00000026      91             swap2                 suc 0 rds
|           0x00000027      602b           push1 0x2b            0x2b suc 0 rds
|       ,=< 0x00000029      57             jumpi                 0 rds
|       |   0x0000002a      fd             revert
|       `-> 0x0000002b      5b             jumpdest              0 rds
\           0x0000002c      f3             return
```

I tried here and could not beat it. I tried using a vanity proxy address (`ADDRESS`) as a jump lookup table using `BYTE`.

Totally different approach, same runtime gas.

**Comment by fulldecent** [comment]
Please update the EIP to include a discussion end date.

**Comment by fulldecent** [comment]
May the amount of gas used for standard deployment, vanity deployment as well as standard and vanity execution?

This seems relevant to the discussion. Also it will be relevant to somebody considering whether to do a vanity deployment.

**Comment by fulldecent** [comment]
Well, the vanity deployment results in a different thing on the blockchain that consumers (etherscan) will need to look for. If we can show that the savings is negligible for vanity then perhaps we can discourage them, making EIP consumers' (etherscan) job easier.

**Comment by yarrumretep** [comment]
Thanks @Recmo @fulldecent @cag - for the comments and discussion.  EIP-1167 has now been promoted to "final" status - and is improved thanks to your feedback and comments!  Rock on!

Closing this issue.

**Comment by fulldecent** [comment]
Can you please let me know your Twitter names so I can do a proper shout out on Twitter?

**Comment by yarrumretep** [comment]
Mine is @yarrumretep

**Comment by flygoing** [comment]
Mines natewelch_

**Comment by flygoing** [comment]
And Joe's is @JosephMesserman

**Comment by SCBuergel** [comment]
What's the status of this EIP?
Once there's actual adoption (e.g. security tokens for many small businesses?) and standardization this would be quite helpful.

**Comment by yarrumretep** [comment]
@SCBuergel - the EIP has been merged / finalized ->http://eips.ethereum.org/EIPS/eip-1167

We haven't created a registry of users at this point, so not sure of utilization in production.  We have started discussions with Etherscan for them to recognize these proxies and provide helpful link-through to the proxied contract for code verification purposes, etc.

**Comment by 0age** [comment]
I know this EIP is already finalized, but I figured I may as well share a marginal improvement (1 less byte, 4 less gas to call) to the implementation here: https://medium.com/@0age/the-more-minimal-proxy-5756ae08ee48
