### ISSUE TITLE
Outdated version of Solidity compiler version.

### ISSUE THREAD

**Issue by Shinwari536** [optionality/clone-factory#25]
Hi,
I am trying to use this library. But the problem is this library is using the 0.4.23 version of the solidity compiler. The library is not compatible with the 0.8 version of the solidity compiler. Can any contributor of this library update it to the latest version?

**Comment by farrukhsydykov** [comment]
~Would love to see an updated version of this repo too!~

Update: Seems like this is not necessary. Use OpenZeppelin's Clones library

**Comment by Shinwari536** [comment]
> ~Would love to see an updated version of this repo too!~
> 
> Update: Seems like this is not necessary. Use OpenZeppelin's Clones library

Yes you are right.
